from django.db import models
import datetime
from django.utils import timezone


class Course(models.Model):
	MAJOR_COLLEGES=(
		('AGR', 'College of Agriculture'),
		('EDU', 'College of Education'),
		('ENGR', 'College of Engineering'),
		('HHSC', 'College of Health and Human Sciences'),
		('LIBA', 'College of Liberal Arts'),
		('PHAR', 'College of Pharmacy'),
		('SCI', 'College of Science'),
		('TECH', 'College of Technology'),
		('VETM', 'College of Veterinary Medicine'),
		('EXPS', 'Exploratory Studies'),
		('MGMT', 'Kranner School of Management'),
		)
	COURSE_MAJORS=(
		('AAE', 'Aeronautical & Astrological Engineering'),
		('AAS', 'African American Studies'),
		('ABE', 'Agricultural and Biological Engineering'),
		('ACC', 'Accounting'),
		('ACE', 'Adult Continuing Education'),
		('ACS', 'Applied Computer Science'),
		('AD', 'Art & Design'),
		('AFRO', 'Afro-American Studies'),
		('AFT', 'Aerospace Studies'),
		('AGEC', 'Agricultural Economics'),
		('AGR', 'Agriculture'),
		('AGRY', 'Agronomy'),
		('AHS', 'Art: History'),
		('AMST', 'American Studies'),
		('ANAT', 'Anatomy'),
		('ANSC', 'Animal Sciences'),
		('ANTH', 'Anthropology'),
		('ARAB', 'Arabic'),
		('ARET', 'Architectural Engineering Technology'),
		('ART', 'Architectural Technology'),
		('AS', 'Administrative Sciences'),
		('ASAM', 'Asian American Studies'),
		('ASCS', 'Arts & Science Career Services'),
		('ASIA', 'Asian Studies'),
		('ASL', 'American Sign Language'),
		('ASM', 'Agricultural Systems Management'),
		('ASTR', 'Astronomy'),
		('AT', 'Aviation Technology'),
		('BA', 'Business Administration'),
		('BAND', 'Bands'),
		('BCHM', 'Biochemistry'),
		('BCM', 'Building Construction Management Technology'),
		('BGR', 'Boiler Gold Rush'),
		('BHS', 'Behavioral Sciences'),
		('BIOL', 'Biological Sciences'),
		('BIOP', 'Biophysics'),
		('BIOS', 'Biostatistics'),
		('BITN', 'Biotechnology'),
		('BIZA', 'Business Analytics'),
		('BME', 'Biomedical Engineering'),
		('BMS', 'Basic Medical Sciences'),
		('BSS', 'Behavioral & Socal Sciences'),
		('BTNY', 'Botany & Plant Pathology'),
		('BUKD', 'Business Kelly Direct'),
		('BUPA', 'Business-Professional Accountancy'),
		('BUS', 'Business'),
		('BUSM', 'Business Management'),
		('CAND', 'Candidate'),
		('CDFS', 'Child Development & Family Studies'),
		('CE', 'Civil Engineering'),
		('CEM', 'Construction Engineering & Management'),
		('CEMT', 'Construction Engineering Management & Technology'),
		('CET', 'Civil Engineering Technology'),
		('CFS', 'Consumer & Family Sciences'),
		('CGT', 'Computer Graphics Technology'),
		('CHE', 'Chemical Engineering'),
		('CHEM', 'Chemistry'),
		('CHHS', 'College of Health & Human Services'),
		('CHM', 'Chemistry'),
		('CHNS', 'Chinese'),
		('CIC', 'Travelling Scholar'),
		('CIMT', 'Computer Integrated Manufatcturing Technology'),
		('CIS', 'Computer Information Services'),
		('CLCS', 'Classics'),
		('CLPH', 'Clinical Pharmacy'),
		('CMCI', 'CIC Common Market'),
		('CMCL', 'Communications & Cultures'),
		('CMET', 'Construction Management & Engineering Technology'),
		('CMPL', 'Comparative Literature'),
		('CNET', 'Construction Engineering Technology'),
		('CNIT', 'Computer & Informational Technology'),
		('COAS', 'College Arts & Sciences'),
		('COGS', 'Cognitive Science'),
		('COLL', 'College of Arts & Science'),
		('COM', 'Communication'),
		('COMM', 'Communication'),
		('CPB', 'Comparative Pathobiology'),
		('CPET', 'Computer Engineering Technology'),
		('CPSY', 'Counselling Psychology'),
		('CRJU', 'Criminal Justice'),
		('CS', 'Computer Science'),
		('CSD', 'Communication Sciences & Disorders'),
		('CSR', 'Consumer Sciences & Retailing'),
		('DANC', 'Dance'),
		('DAST', 'Dental Assisting'),
		('DHYG', 'Dental Hygiene'),
		('DLTP', 'Dental Labratory Technology'),
		('DPIS', 'Data Procurement & Informational Science'),
		('EALC', 'East Asian Language & Culture'),
		('EAPS', 'Earth Atmospheric Planetary Science'),
		('EAS', 'Earth & Atmospheric Science'),
		('ECE', 'Electrical & Computer Engineering'),
		('ECON', 'Economics'),
		('EDCI', 'Education-Curriculum & Instruction'),
		('EDFA', 'Foundations & Administration'),
		('EDHI', 'Education Higher'),
		('EDPS', 'Education-Educational & Psychological Studies'),
		('EDST', 'Educational Leadership & Cultural Foundations'),
		('EEE', 'Environmental & Ecological Engineering'),
		('EEN', 'Energy Engineering'),
		('EMER', 'Emergency Medical Service'),
		('ENE', 'Engineering Education'),
		('ENGL', 'English'),
		('ENGR', "Engineering"),
		('ENTM', 'Entymology'),
		('ENTR', 'Entrepreneurship'),
		('EPCS', 'Engineering Project Community Service'),
		('EQU', 'Equine Management'),
		('ESC', 'Engineering Sciences'),
		('ET', 'Electrical Technology'),
		('ETCS', 'Engineering Technology & Computer Science'),
		('ETHN', 'Ethnic Studies'),
		('EXPL', 'Exploratory Studies'),
		('FCSM', 'Family Consumer Science: Merchandise'),
		('FILM', 'Film Studies'),
		('FIN', 'Finance'),
		('FIS', 'Forensic & Investigational Sciences'),
		('FLL', 'Foreign Language & Literatures'),
		('FLLC', 'Foster International Living/Learning Center'),
		('FM', 'Fitness Management'),
		('FN', 'Foods And Nutrition'),
		('FNR', 'Forestry & Natural Resources'),
		('FOLK', 'Folklore'),
		('FR', 'French'),
		('FRST', 'Foreign Studies'),
		('FS', 'Food Science'),
		('FVS', 'Film And Video Studies'),
		('GBA', 'Business-Accounting'),
		('GBG', 'Business-General'),
		('GBH', 'General Business Health'),
		('GBI', 'Business-International'),
		('GBM', 'BUsiness-Marketing'),
		('GEOG', 'Geography'),
		('GEOL', 'Geology'),
		('GEOS', 'Geosciences'),
		('GEP', 'Global Engineering Program'),
		('GER', 'German'),
		('GERN', 'Gerontology'),
		('GNC', 'Community College'),
		('GNS', 'Community College'),
		('GRAD', 'Graduate Studies'),
		('GREK', 'Greek'),
		('GS', 'General Studies'),
		('HDFS', 'Human Development & Family Studies'),
		('HEBR', 'Hebrew'),
		('HER', 'Herron Art'),
		('HETM', 'Healthcare Engineering Technology Management'),
		('HHS', 'College Healt & Human Sciences'),
		('HIA', 'Health Information Administration'),
		('HIST', 'History'),
		('HK', 'Health & Kinesiology'),
		('HONR', 'Honors'),
		('HORT', 'Horticulture'),
		('HPER', 'Health Physical Ecucation & Recreation'),
		('HPSC', 'History & Philosophy of Science'),
		('HSCI', 'Health Sciences'),
		('HSRV', 'Human Services'),
		('HST', 'Health Studies'),
		('HTM', 'Hospitality & Tourism Management'),
		('HUMA', 'Humanities-General'),
		('IDE', 'Interdisciplinary Engineering'),
		('IDIS', 'Interdisciplinary Studies'),
		('IE', 'Industrial Engineering'),
		('IET', 'Industrial Engineering Technology'),
		('ILCS', 'International Language & Cultural Studies'),
		('IM', 'Informatics'),
		('INTG', 'Integrated Studies'),
		('INTL', 'International'),
		('IPPH', 'Industrial & Physical Pharmacology'),
		('ISM', 'Information Systems'),
		('IST', 'Information Systems & Technology'),
		('IT', 'Industrial Technology'),
		('ITAL', 'Italian'),
		('ITC', 'Information Technology & Computers'),
		('ITCS', 'Industry & Technology: Construction Technology'),
		('ITS', 'Information Technology Systems'),
		('JOUR', 'Journalism'),
		('JPNS', 'Japanese'),
		('JWST', 'Jewish Studies'),
		('KINS', 'Kinsey Institute'),
		('LA', 'Landscape Architecture'),
		('LALS', 'Latin American & Latino Studies'),
		('LAS', "Latin American Studies"),
		('LATN', 'Latin'),
		('LAW', 'Law'),
		('LBST', 'Liberal Studies'),
		('LC', 'Languages and Cultures'),
		('LGBT', 'Lesbian, Gay, Bisexual, & Transgender'),
		('LING', 'Linguistics'),
		('LS', 'Land Surveying'),
		('LSTU', 'Labor Studies'),
		('LTHN', 'Lithuanian'),
		('MA', 'Mathematics'),
		('MARS', 'Midieval & Renaissance Studies'),
		('MATH', 'Mathematics'),
		('MCMP', 'Medical Chemical & Molecular Pharmacology'),
		('ME', 'Mechanical Engineering'),
		('MED', 'Medicine'),
		('MET', 'Mechanical Engineering Technology'),
		('MFET', 'Manufacturing Engineering Technology'),
		('MGEN', 'Medical Genetics'),
		('MGMT', 'Management'),
		('MHHS', 'Medical Humanities & Health Sciences'),
		('MICR', 'Microbiology'),
		('MIS', 'Management Information Systems'),
		('MKG', 'Marketing'),
		('MSCI', 'Medical Sciences'),
		('MSE', 'Materials Engineering'),
		('MSL', 'Military Science & Leadership'),
		('MSPT', 'Motorsports Studies'),
		('MSTD', 'Museum Studies'),
		('MSV', 'Model, Simulation & Visualization'),
		('MT', 'Mathematics'),
		('MUS', 'Music History & Theory'),
		('NELC', 'Near Eastern Languages'),
		('NEWM', 'New Media'),
		('NMCM', 'New Media Communication'),
		('NRES', 'Natural Resources & Environmental Sciences'),
		('NS', 'Naval Science'),
		('NUCL', 'Nuclear Engineering'),
		('NUPH', 'Nuclear Pharmacy'),
		('NUR', 'Nursing'),
		('NUTR', 'Nutrition Science'),
		('OBHR', 'Organizational Behavior & Human Resources'),
		('OLS', 'Organizational Leadership & Supervision'),
		('OVST', 'Overseas Studies'),
		('PACS', 'Peace & Conflict Studies'),
		('PATH', 'Pathology'),
		('PBHL', 'Public Health'),
		('PCTX', 'Pharmacology & Toxicology'),
		('PES', 'Physical Education Skills'),
		('PHAD', 'Pharmacy Administration'),
		('PHIL', 'Philosophy'),
		('PHPR', 'Pharmacy Practice'),
		('PHRM', 'Pharmacy'),
		('PHSL', 'Physiology'),
		('PHST', 'Philanthropic Studies'),
		('PHYS', 'Physics'),
		('PLSC', 'Plant Sciences'),
		('PLSH', 'Polish'),
		('POL', 'Political Science'),
		('PPOL', 'Public Policy'),
		('PPT', 'Professional Practice-Technology'),
		('PSY', 'Psychology'),
		('PTGS', 'Portuguese'),
		('PULM', 'Pulmonary&Critical Care Medicine'),
		('RADI', 'Radiology'),
		('RADX', 'Radiological Science'),
		('RAON', 'Radiation Oncology'),
		('RECR', 'Recreation Leadership'),
		('REG', 'Reg File Maintenance'),
		('REL', 'Religious Studies'),
		('RUSS', 'Russian'),
		('SA', 'Study Abroad'),
		('SCI', 'General Science'),
		('SE', 'Systems Engineering'),
		('SERV', 'Service Learning'),
		('SFS', 'SUstainable Food & Farm Systems'),
		('SHRS', 'School of Health & Rehabilitation Sciences'),
		('SLA', 'School of Liberal Arts'),
		('SLAV', 'Slavic Language & Literature'),
		('SLHS', 'Speech, Language & Hearing Science'),
		('SLIS', 'Lib & Informational Science'),
		('SOC', 'Sociology'),
		('SPAN', 'Spanish'),
		('SPEA', 'Public & Environmental Affairs'),
		('SRCT', 'Serbo-Croation'),
		('STAR', 'Summer Transition Advising & Registration'),
		('STAT', 'Statistics'),
		('SWAH', 'Swahili'),
		('SWRK', 'Social Work'),
		('TCEM', 'Tour Conventions & Event Management'),
		('TCM', 'Technical Communications'),
		('TECH', 'Technology'),
		('THTR', 'Theatre'),
		('TLI', 'Technology Leadership Innovation'),
		('URDU', 'Urdu'),
		('VCD', 'Visual Communication & Design'),
		('VCS', 'Veterinary Clinical Science'),
		('VM', 'Veterinary Medicine'),
		('WGSS', 'Women Gender & Sexuality Studies'),
		('WLAC', 'World Languages & Culture'),
		('WOST', "Women's Studies"),
		('YDAE', 'Youth Development & Agricultural Education'),
		('ZOOL', 'Zoology'),
		)
	course_school = models.CharField(max_length=4, choices=MAJOR_COLLEGES)
	course_major = models.CharField(max_length=4, choices=COURSE_MAJORS)
	course_title = models.CharField(max_length=50)
	course_number = models.IntegerField(default=0)
	course_desc = models.CharField(max_length= 1000)
	course_CRN = models.IntegerField(default=0, unique=True)
	def __str__(self):
		return self.course_title